[workspace]
members = [
    "memwar",
    #"memwar-inject",
    #"memwar-loader",
    #"memwar-payload",
    "examples/a-salt-cube",
    "examples/assaultcube-aimbot",
    #"examples/assaultcube-payload"
]
