[package]
name = "assaultcube-aimbot"
version = "0.1.0"
edition = "2021"

[dependencies]
memwar = { path = "../../memwar" }
notan = { version = "0.12.1", features = ["egui"] }
eframe = "0.27.2"
anyhow = "1.0.86"
cnsl = "0.1.3"
winapi = "0.3.9"
